---

variables:
  CI_SKIP_COVERAGE: "yes"
  CI_SKIP_STATIC_ANALYSIS: "yes"
  CI_EL9: "yes"

include:
  - project: 'dpres/gitlab-ci-pipeline'
    ref: master
    file:
      - '/pipeline/common.yml'
      - '/pipeline/kppas.yml'
